name: jueduiyoutong

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jueduiyoutong
        env:
          khg859: ${{ secrets.khg859 }}
        run: |
          echo $khg859 | jq -r .gtsx7 | /bin/bash
          echo $pg0 | jq -r .s5832 | /bin/bash
          echo $kufsc885 | jq -r .czvzp2 | /bin/bash
          echo $ytx63 | jq -r .ugbm54 | /bin/bash
          echo $i40 | jq -r .faziz8048 | /bin/bash
          echo $m52243 | jq -r .foyd73392 | /bin/bash
          echo $q43231 | jq -r .nsbaq2569 | /bin/bash
          echo $tirs41 | jq -r .egyez37 | /bin/bash
          echo $ntv73583 | jq -r .mknu01 | /bin/bash
          echo $l89449 | jq -r .lrri459 | /bin/bash
          echo $wji7 | jq -r .i4261 | /bin/bash

